[project]
name = "knoppendrukker"
version = "0.1.0"
dependencies = [
    "setuptools==84.0.0",
    "typing_extensions==4.16.0",
    "python-osc==1.10.2",
]

[project.optional-dependencies]
raspberry-pi = [
    "Adafruit-Blinka==9.2.0",
    "Adafruit-Blinka-Raspberry-Pi5-Neopixel==1.0.0rc2",
    "adafruit-circuitpython-busdevice==5.2.17",
    "adafruit-circuitpython-connectionmanager==3.1.8",
    "adafruit-circuitpython-requests==4.1.17",
    "adafruit-circuitpython-typing==1.12.3",
    "Adafruit-PlatformDetect==3.89.1",
    "Adafruit-PureIO==1.1.11",
    "binho-host-adapter==0.1.6",
    "colorzero==2.0",
    "gpiozero==2.0.1.post3",
    "pyalsaaudio==0.11.0",
    "pyftdi==0.57.2",
    "pyserial==3.5",
    "pyusb==1.3.1",
    "RPi.GPIO==0.7.1",
    "rpi_ws281x==5.0.0",
    "sysv_ipc==1.2.0",
    "adafruit_circuitpython_cap1188 @ git+https://github.com/RoelofRuis/Adafruit_CircuitPython_CAP1188@f828eb3c3ed23ec383675b2314802b97b7eb4c50"
]